spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/architecture-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
